#ifndef ADMIN_COLLECTOR_HPP
#define ADMIN_COLLECTOR_HPP

/*

This file is part of Osmium (http://osmcode.org/libosmium).

Copyright 2013-2016 Jochen Topf <jochen@topf.org> and others (see README).

Boost Software License - Version 1.0 - August 17th, 2003

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.

*/

#include <algorithm>
#include <cstddef>
#include <cstring>
#include <vector>

#include <osmium/area/stats.hpp>
#include <osmium/memory/buffer.hpp>
#include <osmium/osm/item_type.hpp>
#include <osmium/osm/location.hpp>
#include <osmium/osm/node_ref.hpp>
#include <osmium/osm/relation.hpp>
#include <osmium/osm/tag.hpp>
#include <osmium/osm/way.hpp>
#include <osmium/relations/collector.hpp>

namespace osmium {

    namespace relations {
        class RelationMeta;
    } // namespace relations
} // namespace osmium

/**
* @brief Code related to the building of areas (multipolygons) from relations.
*/
/**
 * This class collects all data needed for creating areas from
 * relations tagged with type=multipolygon or type=boundary.
 * Most of its functionality is derived from the parent class
 * osmium::relations::Collector.
 *
 * The actual assembling of the areas is done by the assembler
 * class given as template argument.
 *
 * @tparam TAssembler Multipolygon Assembler class.
 */
template <typename TAssembler>
class AdminCollector : public osmium::relations::Collector<AdminCollector<TAssembler>, false, true, false> {

    using collector_type = osmium::relations::Collector<AdminCollector<TAssembler>, false, true, false>;

    using assembler_config_type = typename TAssembler::config_type;
    const assembler_config_type m_assembler_config;

    osmium::memory::Buffer m_output_buffer;

    osmium::area::area_stats m_stats;

    static constexpr size_t initial_output_buffer_size = 1024 * 1024;
    static constexpr size_t max_buffer_size_for_flush = 100 * 1024;

    void flush_output_buffer() {
        if (this->callback()) {
            osmium::memory::Buffer buffer(initial_output_buffer_size);
            using std::swap;
            swap(buffer, m_output_buffer);
            this->callback()(std::move(buffer));
        }
    }

    void possibly_flush_output_buffer() {
        if (m_output_buffer.committed() > max_buffer_size_for_flush) {
            flush_output_buffer();
        }
    }

public:

    explicit AdminCollector(const assembler_config_type& assembler_config) :
        collector_type(),
        m_assembler_config(assembler_config),
        m_output_buffer(initial_output_buffer_size, osmium::memory::Buffer::auto_grow::yes) {
    }

    const osmium::area::area_stats& stats() const noexcept {
        return m_stats;
    }

    /**
     * We are interested in all relations tagged with type=boundary.
     *
     * Overwritten from the base class.
     */
    bool keep_relation(const osmium::Relation& relation) const {
        return relation.tags().has_tag("boundary", "administrative");
    }

    /**
     * Overwritten from the base class.
     */
    bool keep_member(const osmium::relations::RelationMeta& /*relation_meta*/, const osmium::RelationMember& member) const {
        // We are only interested in members of type way.
        return member.type() == osmium::item_type::way;
    }


    void flush() {
        flush_output_buffer();
    }

    osmium::memory::Buffer read() {
        osmium::memory::Buffer buffer(initial_output_buffer_size, osmium::memory::Buffer::auto_grow::yes);

        using std::swap;
        swap(buffer, m_output_buffer);

        return buffer;
    }

}; // class AdminCollector

#endif // ADMIN_COLLECTOR_HPP
